### ISSUE TITLE
Text renders behind other objects in the scene

### ISSUE THREAD

**Issue by anupamdas2012** [bhushan6/babylon-msdf-text#1]
I want to render 3D text in a scene that contains other 3d objects. Seems the text shader does not sort with depth so it renders behind all objects in the scene rather being correctly integrated into the scene .

**Comment by bhushan6** [comment]
Hey @anupamdas2012 , 

Closing this issue since we have solved it [here](https://forum.babylonjs.com/t/msdf-text-rendering/43068/7?u=bhushan_wagh)
